remove_outliers: true
detrend_demean: true
tolerance_s: 0.0
taper: true
initialized: true
p_only: true
station_latitude: '54.72972972972973'
station_longitude: '-1.8098205031446526'
radmax: '90.0'
minmag: '0.0'
maxmag: '10.0'
apply_bandpass: true
network: AM
tolerance_p: 22.0
simplified: false
p_threshold: 0.1
overwrite: false
radmin: '0.0'
denoise: true
catalog_providers: IRIS, USGS, EMSC, GFZ, CENC
detrend_linear: true
data_provider_url: https://data.raspberryshake.org
s_threshold: 0.7
fill_map: true
email_recipient: 891578348@qq.com
station_code: RE83E
enable_automation: true
